name: time_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  package_info_plus: ^8.2.1
  url_launcher: ^6.3.1
  get_it: ^8.0.3
  get_storage: ^2.1.1
  firebase_messaging: ^15.2.2
  webview_flutter: ^4.10.0
  device_info_plus: ^11.3.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  http: ^1.3.0
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl:
  permission_handler: ^11.3.1
  sign_in_with_apple: ^6.1.4
  lottie: ^3.3.1
  provider: ^6.1.2
  fluttertoast: ^8.2.12
  flutter_displaymode: ^0.6.0
  auto_animated: ^3.2.0
  percent_indicator: ^4.2.4
  country_pickers: ^3.0.1
  intl_phone_field: ^3.2.0
  floating_bottom_navigation_bar: ^1.0.0
  animated_bottom_navigation_bar: ^1.4.0
  pinput: ^5.0.1
  device_preview:
  contained_tab_bar_view: ^0.8.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/gen/
  line_length: 500
  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
